import { Controller, Post, Body, UseGuards, Req, Get, Query, Param, ParseIntPipe } from '@nestjs/common';
import { OrdersService } from './orders.service';
import { PaymentsService } from 'src/payments/payments.service';
import { CreateOrderDto } from './dto/create-order.dto';
import { JwtAuthGuard } from 'src/auth/jwt-auth.guard';
import { PaymentType } from './order.entity';

@UseGuards(JwtAuthGuard)
@Controller('orders')
export class OrdersController {
  constructor(
    private ordersService: OrdersService,
    private paymentsService: PaymentsService,
  ) { }

  // 1. Create Order & Get PhonePe SDK Params
  @UseGuards(JwtAuthGuard)
  @Post('initiate')
  async initiateOrder(@Req() req: any, @Body() dto: CreateOrderDto) {
    // 1. Create Order from Cart
    const order = await this.ordersService.createOrderFromCart(req.user, dto.addressId, dto.paymentType);

    // 2. Handle COD Flow
    if (dto.paymentType === PaymentType.COD) {
      await this.ordersService.confirmPayment(order.id, 'COD');
      return {
        paymentUrl: null,
        internalOrderId: order.id,
        status: 'PLACED'
      };
    }

    // 3. Handle Online Payment Flow (Updated for Flutter SDK)
    // ✅ FIX: Call the new method 'getPhonePeSdkParams'
    const paymentData = await this.paymentsService.getPhonePeSdkParams(
      order.totalAmount,
      req.user.id.toString(),
      req.user.phoneNumber || "9999999999" // Fallback if phone is missing
    );

    // Update order with the transaction ID generated by Payment Service
    await this.ordersService.updatePaymentInfo(order.id, paymentData.merchantTransactionId);

    // ✅ Return the specific fields required by the Flutter SDK
    return {
      base64Payload: paymentData.base64Payload,
      checksum: paymentData.checksum,
      merchantTransactionId: paymentData.merchantTransactionId,
      apiEndPoint: paymentData.apiEndPoint,
      packageName: paymentData.packageName,
      callbackUrl: paymentData.callbackUrl,
      internalOrderId: order.id,
      status: 'PENDING'
    };
  }

  // 2. Check Status (Called by Flutter after returning from Payment App)
  @UseGuards(JwtAuthGuard)
  @Get('status')
  async checkStatus(@Query('orderId') orderId: number) {
    return this.ordersService.verifyAndCompleteOrder(orderId);
  }

  @Get()
  async getMyOrders(@Req() req: any) {
    return this.ordersService.findAllByUser(req.user.id);
  }

  @Get(':id')
  async getOrderDetails(@Req() req: any, @Param('id', ParseIntPipe) id: number) {
    return this.ordersService.findOne(id, req.user.id);
  }

  @Get(':id/tracking')
  async getOrderTracking(@Req() req: any, @Param('id', ParseIntPipe) id: number) {
    return this.ordersService.getTrackingDetails(id, req.user.id);
  }
}